//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Pro4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bansaosach
    {
        public string maSach { get; set; }
        public string maBanSao { get; set; }
        public Nullable<int> soThuTu { get; set; }
        public Nullable<int> loaiBanSao { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<int> xoa { get; set; }
    }
}
