//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Pro4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietmuonsach
    {
        public string maThongTinMuonSach { get; set; }
        public string maBanSaoSach { get; set; }
        public Nullable<int> trangThai { get; set; }
        public string ngayMuon { get; set; }
        public string ngayTra { get; set; }
        public Nullable<int> tienPhat { get; set; }
        public string lyDoPhat { get; set; }
    }
}
