//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Pro4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public string tenTaiKhoan { get; set; }
        public string matKhau { get; set; }
        public string ten { get; set; }
        public string gioiTinh { get; set; }
        public string email { get; set; }
        public string soDienThoai { get; set; }
    }
}
