//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Pro4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinmuontrasach
    {
        public string maThongTinMuonTraSach { get; set; }
        public string ngayDangKy { get; set; }
        public string hanTra { get; set; }
        public string trangThai { get; set; }
        public string maNguoiMuon { get; set; }
        public Nullable<int> tienDatCoc { get; set; }
    }
}
